// <auto-generated />
namespace Bug_Lite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MimiTypeExpansion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MimiTypeExpansion));
        
        string IMigrationMetadata.Id
        {
            get { return "201506151345433_MimiTypeExpansion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
